version: "3"
services:
  mongodbtest:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongoexpresstest:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodbtest
    depends_on:
      - mongodbtest
    restart: "on-failure"
  my-app:
    image: my-app:test
    ports:
      - 3000:3000
    depends_on:
      - mongodbtest
      - mongoexpresstest
volumes:
  mongo-data:
   driver: local
